<a href="https://colab.research.google.com/github/bcslayer/SQL/blob/main/Leung_Zoe_2_notebook_022024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ChatData

## Sqlite
We are using a file system called **sqlite**. It looks and acts like a real single user relational database (RDB). sqlite3 comes packaged with python. You do not need to install the library. You simply import it (as below).

- We are using Pandas to write and read to sqlite. Pandas will manage a lot of the complexity of dealing with a RDB. There are other ways of reading and writing to a RDB that are VERY common and often used in production systems.  

- The most common other way is to read or write to the RDB row by row. As you can see Pandas puts the entire dataframe into the RDB or extracts a new dataframe from the RDB. These are not row by row operations. These are set operations. Set operations ARE more efficient. However, it is common to use row by row operations to avoid needing large memory computers to hold the dataframes. One row only takes a few bytes. An entire dataframe could be many gigabytes and even petabytes of data. Obviously you will end up with problems with your compute resource if your files are this big. This will not happen to you in this activity and may never happen to you while you are a data analyst. Please just be aware of this.

- This activity is primarily about querying a RDB, so, we are using a simple way that Pandas provides. If you want to learn the more complex way, just google 'reading and wrting to a relational database using python'. There are many resources to learn from.

- The data types that sqlite supports are quite limited. for example, it does not have a DATE type.  This is not a challenge for this project. However, more sophisticated database systems,such as Postgresql, have a large array of data types, such as "DATE", etc. that give those systems additional capability.

- All of the SQL queries could also be performed on the Pandas DataFrames directly.  You may want to try this yourself for comparison (but make sure you do the SQL queries first, as this is an exercise in using SQL!).


## SQL Magic
Within the Jupyter notebook we will be using something called **SQL Magic**.  This provides a convenient way to write SQL queries directly into code cells in the notebook and to read the results back into a Pandas DataFrame.  This makes working with SQL much easier!

Note that you may need to update your sqlite version using `conda update -c anaconda sqlite` in order for the SQL Magic to work correctly.

## The Data Analysis Lifecycle
The sections in this notebook follow the stages of the Data Analysis Lifecycle introduced in an earlier activity.  The stages are:

- Acquire
- Transform
- Organise
- Analyse
- Communicate
- Maintain

The requirements document for this project is Template SQL queries.xlsx.

# Preliminary Steps: Create a Database
First let's import Sqlite and the other libraries we will need.

In [ ]:
# Import Libraries
import numpy as np
import pandas as pd
import sqlite3

### Create the Database
Now we will create the Sqlite database.  Here is some code that does this for you.  We use the `%load_ext` magic command to load the SQL Magic extension and then use `%sql` to connect to the database.

In [ ]:
# If the db does not exist, sqlite will create it.
con = sqlite3.connect('chatdata.db')

# loads sql magic
%load_ext sql

# connects sql magic command to the correct db
%sql sqlite:///chatdata.db

#### Drop the `queries` table if it already exists
The queries table will be our record of the queries created to answer the questions from the requirements spreadsheet.  As we will be running this Jupyter notebook a few times, let's drop (i.e. remove) the queries table so that we start fresh each time.  Here is the code to do this.  We use the `%%sql` magic command to tell Jupyter that we are going to write SQL in the cell.

In [ ]:
%%sql
DROP TABLE IF EXISTS 'queries'

 * sqlite:///chatdata.db
Done.

[]

# Task 1: Load the Data
Now we can start loading the data.  The tables will be created as we load the data.  

Note that some of these files are quite large, so make sure you have plenty of free memory!

## Lifecycle Stages: Transform and Organise
The data has already been processed into 3 clean data files ready for this project:

- queries.csv
- posts.csv
- comments.csv

We will load these files into our database.

## Lifecycle Stage: Acquire
The data can be found in the OpenClassrooms instructions for this activity.

### Google Drive Integration

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
data_path = '/content/drive/MyDrive/Project 4/chatdata/'

### Load Comments Data into a `comments` table
Now we will load the data from the csv files into our sqlite database.

First we load the csv file into a Pandas dataframe:

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
comments = pd.read_csv(data_path + 'comments.csv')
comments.head()

,Id,PostId,Score,Text,CreationDate,UserId
0,723182,385124,0,@BenBolker I don't understand. The fit cannot ...,2019-01-01 00:06:39,78575
1,723183,385124,3,"You can't add *less* than (`-min(y)`), but you...",2019-01-01 00:09:22,2126
2,723186,385137,0,nice. If you felt like doing the work it would...,2019-01-01 00:32:11,2126
3,723187,385137,0,"i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,si...",2019-01-01 00:40:36,2126
4,723188,385134,0,"Don't you mean ""so variance should be $\sigma^...",2019-01-01 00:41:28,112141

Now take the comments dataframe and push the data into the Sqlite database table called 'comments':

In [ ]:
# load comments into sqlite
comments.to_sql('comments', con, if_exists='replace', index=False)

# read back in to prove that it worked
sql = 'SELECT * FROM comments'
comments = pd.read_sql(sql, con)
comments.head()

,Id,PostId,Score,Text,CreationDate,UserId
0,723182,385124,0,@BenBolker I don't understand. The fit cannot ...,2019-01-01 00:06:39,78575
1,723183,385124,3,"You can't add *less* than (`-min(y)`), but you...",2019-01-01 00:09:22,2126
2,723186,385137,0,nice. If you felt like doing the work it would...,2019-01-01 00:32:11,2126
3,723187,385137,0,"i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,si...",2019-01-01 00:40:36,2126
4,723188,385134,0,"Don't you mean ""so variance should be $\sigma^...",2019-01-01 00:41:28,112141

### Load Other CSVs
Now that you have seen the code for loading in the comments.csv now do the same to read and write the posts.csv and users.csv to sqlite.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter code in the following cells. Insert as many cells as you want to do this.
    </font></div>

In [ ]:
# load posts into a "posts" table
posts = pd.read_csv(data_path + 'posts.csv')
posts.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,423497,1,423511,0,2019-08-24 09:39:31,2,68,"<p>From wikipedia <a href=""https://en.wikipedi...",64552,NaN,...,NaN,NaN,2019-08-24 11:38:54,When are biased estimators with lower MSE pref...,<bias><unbiased-estimator><mse>,1,0,1,2019-08-25 10:25:24,NaN
1,423498,1,0,0,2019-08-24 09:47:42,1,24,<p>I am currently doing local sensitivity anal...,87231,NaN,...,NaN,2019-09-06 12:52:32,2019-09-06 12:52:32,How to interpret the result from local sensiti...,<sensitivity-analysis><elasticity>,1,0,0,NaN,NaN
2,423499,1,0,0,2019-08-24 09:48:26,1,56,<p>I'm an honours student in psychology doing ...,257207,NaN,...,NaN,NaN,2019-08-25 08:54:17,Power Analysis in G-Power - Mixed Model Anova,<anova><gpower>,2,0,0,NaN,NaN
3,423500,2,0,215865,2019-08-24 09:57:01,0,0,"<p>Maybe you can look this <a href=""https://me...",106606,NaN,...,NaN,NaN,2019-08-24 09:57:01,NaN,NaN,0,0,0,NaN,NaN
4,423502,2,0,423286,2019-08-24 10:44:52,3,0,<blockquote>\n <p>Q1) Is my approach valid?</...,220643,NaN,...,NaN,2019-08-24 12:13:46,2019-08-24 12:13:46,NaN,NaN,0,1,0,NaN,NaN

In [ ]:
# load posts into sqlite
posts.to_sql('posts', con, if_exists= 'replace', index=False)

# read back in to prove that it worked
sql = 'SELECT * FROM posts'
posts = pd.read_sql(sql, con)
posts.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,423497,1,423511,0,2019-08-24 09:39:31,2,68,"<p>From wikipedia <a href=""https://en.wikipedi...",64552,None,...,None,None,2019-08-24 11:38:54,When are biased estimators with lower MSE pref...,<bias><unbiased-estimator><mse>,1,0,1,2019-08-25 10:25:24,None
1,423498,1,0,0,2019-08-24 09:47:42,1,24,<p>I am currently doing local sensitivity anal...,87231,None,...,None,2019-09-06 12:52:32,2019-09-06 12:52:32,How to interpret the result from local sensiti...,<sensitivity-analysis><elasticity>,1,0,0,None,None
2,423499,1,0,0,2019-08-24 09:48:26,1,56,<p>I'm an honours student in psychology doing ...,257207,None,...,None,None,2019-08-25 08:54:17,Power Analysis in G-Power - Mixed Model Anova,<anova><gpower>,2,0,0,None,None
3,423500,2,0,215865,2019-08-24 09:57:01,0,0,"<p>Maybe you can look this <a href=""https://me...",106606,None,...,None,None,2019-08-24 09:57:01,None,None,0,0,0,None,None
4,423502,2,0,423286,2019-08-24 10:44:52,3,0,<blockquote>\n <p>Q1) Is my approach valid?</...,220643,None,...,None,2019-08-24 12:13:46,2019-08-24 12:13:46,None,None,0,1,0,None,None

In [ ]:
# load users data into a "users" table
users = pd.read_csv(data_path + 'users.csv')
users.columns

Index(['Id', 'Reputation', 'CreationDate', 'DisplayName', 'LastAccessDate',
       'WebsiteUrl', 'Location', 'AboutMe', 'Views', 'UpVotes', 'DownVotes',
       'ProfileImageUrl', 'AccountId'],
      dtype='object')

In [ ]:
# load users into sqlite
users.to_sql('users', con, if_exists="replace", index=False)

# read back in to prove that it work
sql = "SELECT * FROM users"
users = pd.read_sql(sql, con)
users.head()

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,ProfileImageUrl,AccountId
0,157607,31,2017-04-17 14:50:42,user157607,2019-07-23 16:44:08,None,None,None,0,0,0,https://www.gravatar.com/avatar/2efb161849efa4...,10705183
1,157656,101,2017-04-17 20:08:20,user102859,2019-06-26 13:42:13,None,None,None,3,0,0,https://i.stack.imgur.com/eY4ka.jpg?s=128&g=1,10567606
2,157704,133,2017-04-18 05:10:47,jupiar,2019-11-25 13:32:27,None,"Shanghai, China","<p>Originally from the U.K, I have an Undergra...",1,1,0,https://www.gravatar.com/avatar/720e20205122c5...,9501631
3,157709,155,2017-04-18 06:39:18,farmer,2019-02-17 19:44:24,None,None,None,16,0,0,https://www.gravatar.com/avatar/0f8c4bde3d8f25...,10709837
4,157755,101,2017-04-18 12:56:17,Miki P,2019-08-12 17:02:21,None,None,None,1,9,0,https://www.gravatar.com/avatar/af088558cd81c5...,7969290

In [ ]:
comments.dtypes

Id               int64
PostId           int64
Score            int64
Text            object
CreationDate    object
UserId           int64
dtype: object

### **TODO**: Drop Duplicates
Look for and drop any duplicates in all 3 of the tables (if they exist). Use Pandas to do this. If you find duplicates, you will need to rewrite the table.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter code in the following cells.
    </font></div>

In [ ]:
comments.shape

(50000, 6)

In [ ]:
# Drop duplicates in comments
comments = comments.drop_duplicates(subset =["Id"])

In [ ]:
comments.shape

(50000, 6)

In [ ]:
# No duplicates Id in comment dataset

In [ ]:
posts.shape

(42234, 21)

In [ ]:
# Drop duplicates in posts
posts = posts.drop_duplicates(subset =['Id'])

In [ ]:
posts.shape

(42234, 21)

In [ ]:
# No duplicates in posts dataset

In [ ]:
users.shape

(18412, 13)

In [ ]:
# Drop duplciates in users
users = users.drop_duplicates(subset=['Id'])
users.shape

(18412, 13)

In [ ]:
# No duplciates in users dataset
# No duplicates in all three datasets

## Review the Data

Spend some time reviewing the data.  Understand what data we have, think about how that data can be used to assist in the initiative of understanding how ChatData is used in the real world.  Is the data organised in a way that would lend itself to being manged in a relational database?  How would the different tables be connected?  What are the primary and foreign keys?  Would this give you a 3NF model?

Also think about security and ethics.  Is there personal data in here?  Could individuals be identified through this data?  It it ethical to use the data in this way?  You will be asked to comment on these questions later!

Use the code below to help you.

In [ ]:
users.columns

Index(['Id', 'Reputation', 'CreationDate', 'DisplayName', 'LastAccessDate',
       'WebsiteUrl', 'Location', 'AboutMe', 'Views', 'UpVotes', 'DownVotes',
       'ProfileImageUrl', 'AccountId'],
      dtype='object')

In [ ]:
users.head()

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,ProfileImageUrl,AccountId
0,157607,31,2017-04-17 14:50:42,user157607,2019-07-23 16:44:08,None,None,None,0,0,0,https://www.gravatar.com/avatar/2efb161849efa4...,10705183
1,157656,101,2017-04-17 20:08:20,user102859,2019-06-26 13:42:13,None,None,None,3,0,0,https://i.stack.imgur.com/eY4ka.jpg?s=128&g=1,10567606
2,157704,133,2017-04-18 05:10:47,jupiar,2019-11-25 13:32:27,None,"Shanghai, China","<p>Originally from the U.K, I have an Undergra...",1,1,0,https://www.gravatar.com/avatar/720e20205122c5...,9501631
3,157709,155,2017-04-18 06:39:18,farmer,2019-02-17 19:44:24,None,None,None,16,0,0,https://www.gravatar.com/avatar/0f8c4bde3d8f25...,10709837
4,157755,101,2017-04-18 12:56:17,Miki P,2019-08-12 17:02:21,None,None,None,1,9,0,https://www.gravatar.com/avatar/af088558cd81c5...,7969290

In [ ]:
comments.columns

Index(['Id', 'PostId', 'Score', 'Text', 'CreationDate', 'UserId'], dtype='object')

In [ ]:
comments.head()

,Id,PostId,Score,Text,CreationDate,UserId
0,723182,385124,0,@BenBolker I don't understand. The fit cannot ...,2019-01-01 00:06:39,78575
1,723183,385124,3,"You can't add *less* than (`-min(y)`), but you...",2019-01-01 00:09:22,2126
2,723186,385137,0,nice. If you felt like doing the work it would...,2019-01-01 00:32:11,2126
3,723187,385137,0,"i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,si...",2019-01-01 00:40:36,2126
4,723188,385134,0,"Don't you mean ""so variance should be $\sigma^...",2019-01-01 00:41:28,112141

In [ ]:
posts.columns

Index(['Id', 'PostTypeId', 'AcceptedAnswerId', 'ParentId', 'CreationDate',
       'Score', 'ViewCount', 'Body', 'OwnerUserId', 'OwnerDisplayName',
       'LastEditorUserId', 'LastEditorDisplayName', 'LastEditDate',
       'LastActivityDate', 'Title', 'Tags', 'AnswerCount', 'CommentCount',
       'FavoriteCount', 'ClosedDate', 'CommunityOwnedDate'],
      dtype='object')

In [ ]:
posts.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,423497,1,423511,0,2019-08-24 09:39:31,2,68,"<p>From wikipedia <a href=""https://en.wikipedi...",64552,None,...,None,None,2019-08-24 11:38:54,When are biased estimators with lower MSE pref...,<bias><unbiased-estimator><mse>,1,0,1,2019-08-25 10:25:24,None
1,423498,1,0,0,2019-08-24 09:47:42,1,24,<p>I am currently doing local sensitivity anal...,87231,None,...,None,2019-09-06 12:52:32,2019-09-06 12:52:32,How to interpret the result from local sensiti...,<sensitivity-analysis><elasticity>,1,0,0,None,None
2,423499,1,0,0,2019-08-24 09:48:26,1,56,<p>I'm an honours student in psychology doing ...,257207,None,...,None,None,2019-08-25 08:54:17,Power Analysis in G-Power - Mixed Model Anova,<anova><gpower>,2,0,0,None,None
3,423500,2,0,215865,2019-08-24 09:57:01,0,0,"<p>Maybe you can look this <a href=""https://me...",106606,None,...,None,None,2019-08-24 09:57:01,None,None,0,0,0,None,None
4,423502,2,0,423286,2019-08-24 10:44:52,3,0,<blockquote>\n <p>Q1) Is my approach valid?</...,220643,None,...,None,2019-08-24 12:13:46,2019-08-24 12:13:46,None,None,0,1,0,None,None

# Working with Sqlite and SQL Magic
In this section let's spend a little time understanding a bit more about how we can work with Sqlite within Jupyter.

Let's look at 2 ways to query the sqlite database: using SQL Magic or using Pandas.  Either way is fine for this project.

## Writing queries with SQL Magic

You will now need to write some queries to get answers to the questions in the requirements.  

For single-line queries, start the cell with `%sql` and simply enter your query:

In [ ]:
# This is an example
%sql SELECT COUNT(*) FROM comments

 * sqlite:///chatdata.db
Done.

[(50000,)]

In [ ]:
%sql SELECT COUNT(*) FROM users

 * sqlite:///chatdata.db
Done.

[(18412,)]

In [ ]:
%sql SELECT COUNT(*) FROM posts

 * sqlite:///chatdata.db
Done.

[(42234,)]

For multi line sql statements use `%%sql` as follows. This tells Jupyter that *everything* in this cell should be interpreted as sql. So, NO comments other statements are allowed:

In [ ]:
%%sql
SELECT Id, PostId, Score, Text
    FROM comments
        LIMIT 5

 * sqlite:///chatdata.db
Done.

[(723182, 385124, 0, '@BenBolker I don\'t understand. The fit cannot be done for the negative $y$. So intuitively I\'d think that in order to retain the relativity of the  ... (24 characters truncated) ... rror" or "flip" it to the positive axis? Would it be possible to adjust every point individually? Basically e.g. take $abs(y_i)$ instead of minimums.'),
 (723183, 385124, 3, "You can't add *less* than (`-min(y)`), but you could add *more*. I'm going to stop answering now sorry, because **judging what the 'best' approach is ... (60 characters truncated) ...  of the analysis, why you need to fit an exponential, your level of computational and statistical sophistication and that of your audience, etc. ...)"),
 (723186, 385137, 0, 'nice. If you felt like doing the work it would be nice to generate an image/contour plot of log-likelihood as a function of (mu, theta) and show the lines corresponding to the two `size` values .'),
 (723187, 385137, 0, 'i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,size=size,log=TRUE)),\n                 xlim=c(2,5),ylim=c(0.2,0.5),\n                 varnames=c("mu","s ... (57 characters truncated) ... ,col="red")\nabline(h=fit.what$theta,col="blue")\n` ... although doesn\'t look this is actually the answer - mu-hat is independent of theta-hat ... ?'),
 (723188, 385134, 0, 'Don\'t you mean "so variance should be $\\sigma^2/(n\\mu^2)$"')]

## Writing queries with Pandas
Another way to write queries is to use pandas:

In [ ]:
sql = """
SELECT Id, PostId, Score, Text
    FROM comments
        LIMIT 5
        """
result = pd.read_sql(sql, con)
result

       Id  PostId  Score                                               Text
0  723182  385124      0  @BenBolker I don't understand. The fit cannot ...
1  723183  385124      3  You can't add *less* than (`-min(y)`), but you...
2  723186  385137      0  nice. If you felt like doing the work it would...
3  723187  385137      0  i.e. `emdbook::curve3d(-sum(dnbinom(y,mu=mu,si...
4  723188  385134      0  Don't you mean "so variance should be $\sigma^...

# Creating Tables with Referential Integrity

When we loaded the csv files into Sqlite database tables, Sqlite created the tables for us behind the scenes. Let's inspect this a bit more.

We can see how Sqlite created the tables by querying the `sqlite_master` table, which Sqlite uses to keep track of what objects have been created in the database:

In [ ]:
%%sql
select sql from sqlite_master

 * sqlite:///chatdata.db
Done.

[('CREATE TABLE "comments" (\n"Id" INTEGER,\n  "PostId" INTEGER,\n  "Score" INTEGER,\n  "Text" TEXT,\n  "CreationDate" TEXT,\n  "UserId" INTEGER\n)',),
 ('CREATE TABLE "posts" (\n"Id" INTEGER,\n  "PostTypeId" INTEGER,\n  "AcceptedAnswerId" INTEGER,\n  "ParentId" INTEGER,\n  "CreationDate" TEXT,\n  "Scor ... (240 characters truncated) ...   "Tags" TEXT,\n  "AnswerCount" INTEGER,\n  "CommentCount" INTEGER,\n  "FavoriteCount" INTEGER,\n  "ClosedDate" TEXT,\n  "CommunityOwnedDate" TEXT\n)',),
 ('CREATE TABLE "users" (\n"Id" INTEGER,\n  "Reputation" INTEGER,\n  "CreationDate" TEXT,\n  "DisplayName" TEXT,\n  "LastAccessDate" TEXT,\n  "WebsiteUr ... (17 characters truncated) ... tion" TEXT,\n  "AboutMe" TEXT,\n  "Views" INTEGER,\n  "UpVotes" INTEGER,\n  "DownVotes" INTEGER,\n  "ProfileImageUrl" TEXT,\n  "AccountId" INTEGER\n)',)]

The above results show the `CREATE TABLE` statements that could be used by Sqlite to recreate the tables with the exact same structure.

The problem with the CREATE TABLE statements above is that they don't enforce **referential integrity**.  In other words, they don't ensure that every UserId and PostId in the comments table refers to an actual UserId and PostId in the users and posts tables.  At the moment. we can insert any old number here, and even have multiple users with the same Id!  One of the advantages of working with relational databases is that they can enforce the correct uniqueness and relationships in the data, but at the moment we are not using that feature.  So let's fix that...

First, let's drop the original tables:

In [ ]:
%%sql
DROP TABLE comments;
DROP TABLE users;
DROP TABLE posts;

 * sqlite:///chatdata.db
Done.
Done.
Done.

[]

Prove that this worked by selecting the names of the tables back.  We should have no tables:

In [ ]:
%%sql
SELECT name FROM sqlite_master WHERE type='table'
    ORDER BY name

 * sqlite:///chatdata.db
Done.

[]

In Sqlite we need to enable the enforcement of foreign key constraints:

In [ ]:
%%sql
PRAGMA foreign_keys=ON;

 * sqlite:///chatdata.db
Done.

[]

Now recreate the users table with a **primary key constraint** by copying the CREATE TABLE statement from above and adding the NOT NULL PRIMARY KEY clause to the Id:

In [ ]:
%%sql
CREATE TABLE "users" (
"Id" INTEGER NOT NULL PRIMARY KEY,
"Reputation" INTEGER,
"CreationDate" TEXT,
"DisplayName" TEXT,
"LastAccessDate" TEXT,
"WebsiteUrl" TEXT,
"Location" TEXT,
"AboutMe" TEXT,
"Views" INTEGER,
"UpVotes" INTEGER,
"DownVotes" INTEGER,
"ProfileImageUrl" TEXT,
"AccountId" INTEGER
);

 * sqlite:///chatdata.db
Done.

[]

Now do the same for the posts table:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [ ]:
# Run the CREATE TABLE statement for the posts table, including the primary key constraint
%%sql
CREATE TABLE "posts" (
"Id" INTEGER NOT NULL PRIMARY KEY,
"PostTypeId" INTEGER,
"AcceptedAnswerId" INTEGER,
"ParentId" INTEGER,
"CreationDate" TEXT,
"Score" INTEGER,
"ViewCount" INTEGER,
"Body" TEXT,
"OwnerUserId" INTEGER,
"OwnerDisplayName" TEXT,
"LastEditorUserId" INTEGER,
"LastEditorDisplayName" TEXT,
"LastEditDate" TEXT,
"LastActivityDate" TEXT,
"Title" TEXT,
"Tags" TEXT,
"AnswerCount" INTEGER,
"CommentCount" INTEGER,
"FavoriteCount" INTEGER,
"ClosedDate" TEXT,
"CommunityOwnedDate" TEXT
);

 * sqlite:///chatdata.db
Done.

[]

Now for the comments table.  We need to add the primary key constraint on the id here as we did for users and posts, but we also need to add FOREIGN KEY constraints on the UserId and PostId. Read the documentation here and find our how to do that: https://www.sqlite.org/foreignkeys.html.  Then create the comments table with the correct constraints:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [ ]:
# Run the CREATE TABLE statement for the comments table, including the primary key constraint and the 2 foreign key constraints

%%sql
CREATE TABLE "comments" (
"Id" INTEGER NOT NULL PRIMARY KEY,
"PostId" INTEGER,
"Score" INTEGER,
"Text" TEXT,
"CreationDate" TEXT,
"UserId" INTEGER,
FOREIGN KEY (PostId)
  REFERENCES posts (Id),
FOREIGN KEY (UserId)
  REFERENCES users (Id)
);

 * sqlite:///chatdata.db
Done.

[]

Now we can re-insert the data into these constrained tables.  First users:

In [ ]:
# Insert data into the new users table
users.to_sql('users', con, if_exists='append', index=False)

18412

Now posts:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [ ]:
# Insert data into the new posts table
posts.to_sql('posts', con, if_exists='append', index=False)

42234

Finally comments, which references the users and posts tables:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [ ]:
# Insert data into the new comments table
comments.to_sql('comments', con, if_exists='append', index=False)

50000

Now check that we have the 3 new table definitions in Sqlite:

In [ ]:
%%sql
SELECT name FROM sqlite_master WHERE type='table'
    ORDER BY name

 * sqlite:///chatdata.db
Done.

[('comments',), ('posts',), ('users',)]

We now have all the data in tables in Sqlite and the tables will enforce the referential integrity.

# Example Query and Pattern for Tasks 2 and 3

As you work through the next tasks, you will need to:

1. Prepare the Sqlite query to answer the question
2. Test it
3. Insert it into the `queries` table, so we have a record of it for others.

This is the process that we want you to follow for this project while completing it.

Let's see an example of this by answering the following question:

**Which 5 users have viewed the most times and what is the sum of those views per user?**

## Prepare the Sqlite query

First, let's write the query:

In [ ]:
sql = """
SELECT Id, SUM(Views) AS TotalViews
    FROM Users
        GROUP BY Id
            ORDER BY TotalViews DESC
                LIMIT 5
                """
result = pd.read_sql(sql, con) # con is the connection to the database
result

     Id  TotalViews
0   919       85180
1  4253       35119
2   805       34637
3  7290       32639
4  3277       29255

## Test the query
You can optionally prove the query worked by performing the same query in Pandas:

In [ ]:
results = users.groupby(['Id']).sum().sort_values('Views', ascending = False)[:5]
results['Views']

<ipython-input-47-7b2c47bab8fa>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  results = users.groupby(['Id']).sum().sort_values('Views', ascending = False)[:5]

Id
919     85180
4253    35119
805     34637
7290    32639
3277    29255
Name: Views, dtype: int64

## Insert the query into the `queries` table
Now we need to put this query into the `queries` table in sqlite. Remember we want these queries to be accessible to everybody that should have access to them. We do not want people writing and rewriting the same queires over and over again. The easiest thing to do is create a dictionary with the values and insert these into the queries table.  Note that the values are provided as lists as we are inserting a list of values (i.e. a number of rows) into the table.  In this case the number of rows is 1, so we have lists of 1 item.

So here, we have a column called 'task' with a list of values, a column called 'action' with a list of values, etc.

In [ ]:
query_dict = {
              'task': ['Single Table Queries'],
              'action': ['Which 5 users have viewed the most times and what is the sum of those views per user?'],
              'query': [sql]
             }
query_dict

{'task': ['Single Table Queries'],
 'action': ['Which 5 users have viewed the most times and what is the sum of those views per user?'],
 'query': ['\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                ']}

Now that you have the data structure (query_dict) containing the data, create a pandas dataframe that holds those values:

In [ ]:
queries = pd.DataFrame(query_dict)
queries

,task,action,query
0,Single Table Queries,Which 5 users have viewed the most times and w...,"\nSELECT Id, SUM(Views) AS TotalViews\n FRO..."

Now load that pandas dataframe (queries) into the sqlite table called queries. In this case, you use append NOT replace. You will be adding to this tables as you go thru this project.

In [ ]:
# load query into sqlite
queries.to_sql('queries', con, if_exists='append', index=False)

# read back in to prove that it worked
sql = 'SELECT * FROM queries'
queries = pd.read_sql(sql, con)
queries.head()

,task,action,query
0,Single Table Queries,Which 5 users have viewed the most times and w...,"\nSELECT Id, SUM(Views) AS TotalViews\n FRO..."

It is likely that as you iterate thru this notebook you will create some duplicate entries in the query table. Not a big deal. Just tell sql or pandas (much easier in pandas) to drop the duplicates! If you drop the duplicates in Pandas you will have to write the entire dataframe back to sqlite. Otherwise it is changed in memory in Pandas but NOT in sqlite on the disk drive (or SDD). Just do this drop at the end of this notebook so that you are not constantly dealing with this.

So, to summarise, as you go through the following tasks you need to:

- answer the question in sql
- prove it in pandas (if you want to)
- put the query into the queries table

# Task 1 (continued): Insert the CREATE TABLE Statements into the `queries` Table

Now that we understand how to populate the `queries` table, let's insert the CREATE TABLE statements into it.  First let's define a function to help us insert into the queries table:

In [ ]:
# Define a function that will insert into the queries table
def store_query(task, action, query):
    query_dict = {
                  'task': [task],
                  'action': [action],
                  'query': [query]
                 }

    # put query into the query_dict
    queries = pd.DataFrame(query_dict)

    # load query into sqlite
    queries.to_sql('queries', con, if_exists='append', index=False)

Now we can specify the queries and call the above function to store them.  The first one is done for you.

In [ ]:
sql = """
    CREATE TABLE "comments" (
    "Id" INTEGER,
    "PostId" INTEGER,
    "Score" INTEGER,
    "Text" TEXT,
    "CreationDate" TEXT,
    "UserId" INTEGER
    )
    """
store_query("Task 1", "Create table comments", sql)

Let's prove it works by selecting back from the queries table:

In [ ]:
# Prove it works
%sql SELECT * FROM queries

 * sqlite:///chatdata.db
Done.

[('Single Table Queries', 'Which 5 users have viewed the most times and what is the sum of those views per user?', '\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                '),
 ('Task 1', 'Create table comments', '\n    CREATE TABLE "comments" (\n    "Id" INTEGER,\n    "PostId" INTEGER,\n    "Score" INTEGER,\n    "Text" TEXT,\n    "CreationDate" TEXT,\n    "UserId" INTEGER\n    )\n    ')]

## Insert the other CREATE TABLE statements into the `queries` table.
Follow the above pattern to complete these code cells:

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cells
    </font></div>

In [ ]:
# Insert the CREATE TABLE for posts into the queries table
sql = """
    CREATE TABLE "posts" (
    "Id" INTEGER NOT NULL PRIMARY KEY,
    "PostTypeId" INTEGER,
    "AcceptedAnswerId" INTEGER,
    "ParentId" INTEGER,
    "CreationDate" TEXT,
    "Score" INTEGER,
    "ViewCount" INTEGER,
    "Body" TEXT,
    "OwnerUserId" INTEGER,
    "OwnerDisplayName" TEXT,
    "LastEditorUserId" INTEGER,
    "LastEditorDisplayName" TEXT,
    "LastEditDate" TEXT,
    "LastActivityDate" TEXT,
    "Title" TEXT,
    "Tags" TEXT,
    "AnswerCount" INTEGER,
    "CommentCount" INTEGER,
    "FavoriteCount" INTEGER,
    "ClosedDate" TEXT,
    "CommunityOwnedDate" TEXT
    )
    """
store_query("Task 1", "Create table posts" ,sql)

In [ ]:
# Insert the CREATE TABLE for users into the queries table
sql="""
  CREATE TABLE "comments" (
  "Id" INTEGER NOT NULL PRIMARY KEY,
  "PostId" INTEGER,
  "Score" INTEGER,
  "Text" TEXT,
  "CreationDate" TEXT,
  "UserId" INTEGER,
  FOREIGN KEY (PostId)
    REFERENCES posts (Id),
  FOREIGN KEY (UserId)
    REFERENCES users (Id)
  )
  """
store_query("Task 1", "Create table users", sql)

In [ ]:
%sql SELECT * FROM queries

 * sqlite:///chatdata.db
Done.

[('Single Table Queries', 'Which 5 users have viewed the most times and what is the sum of those views per user?', '\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                '),
 ('Task 1', 'Create table comments', '\n    CREATE TABLE "comments" (\n    "Id" INTEGER,\n    "PostId" INTEGER,\n    "Score" INTEGER,\n    "Text" TEXT,\n    "CreationDate" TEXT,\n    "UserId" INTEGER\n    )\n    '),
 ('Task 1', 'Create table posts', '\n    CREATE TABLE "posts" (\n    "Id" INTEGER NOT NULL PRIMARY KEY,\n    "PostTypeId" INTEGER,\n    "AcceptedAnswerId" INTEGER,\n    "ParentId" INTE ... (321 characters truncated) ... "AnswerCount" INTEGER,\n    "CommentCount" INTEGER,\n    "FavoriteCount" INTEGER,\n    "ClosedDate" TEXT,\n    "CommunityOwnedDate" TEXT\n    )\n    '),
 ('Task 1', 'Create table users', '\n  CREATE TABLE "comments" (\n  "Id" INTEGER NOT NULL PRIMARY KEY,\n  "PostId" INTEGER,\n  "Score" INTEGER,\n  "Text" TEXT,\n  "CreationDate" TEXT,\n  "UserId" INTEGER,\n  FOREIGN KEY (PostId)\n    REFERENCES posts (Id),\n  FOREIGN KEY (UserId)\n    REFERENCES users (Id)\n  )\n  ')]

## Count the Number of Rows in Each Table
Run some queries to count the number of rows in each of the tables.  Don't forget to insert the query into the queries table.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cells
    </font></div>

In [ ]:
# Count the number of rows in the comments table
sql = """
    SELECT COUNT(*) FROM comments
    """
result = pd.read_sql(sql, con)
result

   COUNT(*)
0     50000

In [ ]:
# Insert query to the queries table
store_query("Task 1", "Count the number of rows in the comments table", sql)

In [ ]:
# Count the number of rows in the users table
sql = """
    SELECT COUNT(*) FROM users
    """
result = pd.read_sql(sql, con)
result

   COUNT(*)
0     18412

In [ ]:
# Insert query to the queries table
store_query("Task 1", "Count the number of rows in the users table", sql)

In [ ]:
# Count the number of rows in the posts table
sql = """
    SELECT COUNT(*) FROM posts
    """
result = pd.read_sql(sql, con)
result

   COUNT(*)
0     42234

In [ ]:
# Insert query to the queries table
store_query("Task 1", "Count the number of rows in the posts table", sql)

## Do some Random Checks on the Data
Let's write some queries that select 5 random rows from each table.  The queries are provided here:

    select * from Comments order by random() limit 5;
    select * from Users order by random() limit 5;
    select * from Posts order by random() limit 5;

Enter the queries into the code cells below and insert the queries into the `queries` table in the same was as you did for the CREATE TABLE statements.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cells
    </font></div>

In [ ]:
# Run the query to select 5 random rows from the comments table
sql = """
    SELECT * FROM comments order by random() limit 5
    """
result = pd.read_sql(sql, con)
result

,Id,PostId,Score,Text,CreationDate,UserId
0,759313,406306,0,Welcome to cross validated. I think your use c...,2019-05-02 21:52:37,89649
1,781035,418201,0,Thanks for the response!,2019-07-22 20:44:58,253515
2,758062,405507,0,I've added the full code of what i'm attemptin...,2019-04-28 16:49:23,36837
3,787445,421979,0,But what other statements would you like to ma...,2019-08-13 19:10:42,20273
4,762212,407642,0,But what's the use of knowing that the sign fl...,2019-05-12 14:25:33,48591

In [ ]:
# Insert query to the queries table
store_query("Task 1", "Run the query to select 5 random rows from the comments table", sql )

In [ ]:
# Run the query to select 5 random rows from the users table
sql = """
    SELECT * FROM users order by random() limit 5
    """
result = pd.read_sql(sql, con)
result

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,AboutMe,Views,UpVotes,DownVotes,ProfileImageUrl,AccountId
0,204452,11,2018-04-15 10:42:33,Kieran108,2019-10-30 16:55:58,https://warwick.ac.uk/fac/sci/mathsys/people/s...,"Coventry, United Kingdom",<p>PhD student working on large scale data ana...,3,0,0,https://www.gravatar.com/avatar/2ab238ebd86a94...,11827848
1,212593,101,2018-06-24 16:30:04,Attack68,2019-11-22 12:25:09,None,None,None,0,0,0,https://www.gravatar.com/avatar/97ca17a34b5f7b...,8858891
2,8365,1,2012-01-06 03:55:38,anil,2019-11-22 23:48:07,http://Starkey.com,"Berkeley, CA",HCI researcher interested in adaptive user int...,0,0,0,None,95962
3,167191,1,2017-06-29 13:29:10,laz,2019-07-09 16:00:52,None,None,None,3,0,0,None,11075887
4,255138,1,2019-07-30 10:31:39,user255138,2019-07-31 13:47:08,None,None,None,1,0,0,None,16414544

In [ ]:
# Insert query to the queries table
store_query("Task 1", "Run the query to select 5 random rows from the users table", sql )

In [ ]:
# Run the query to select 5 random rows from the posts table
sql = """
    SELECT * FROM posts order by random() limit 5
    """
result = pd.read_sql(sql, con)
result

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,405938,2,0,359242,2019-04-30 21:15:38,0,0,<p>The standard answer on this one is to boots...,86652,None,...,None,None,2019-04-30 21:15:38,None,None,0,0,0,None,None
1,415705,2,0,398035,2019-07-02 14:37:36,0,0,<p>You can try other similar clustering method...,252561,None,...,None,None,2019-07-02 14:37:36,None,None,0,0,0,None,None
2,411366,2,0,411290,2019-06-03 16:04:44,1,0,<p>(I'm sure we have some answers of this ques...,4598,None,...,None,None,2019-06-03 16:04:44,None,None,0,0,0,None,None
3,429540,2,0,379799,2019-10-01 14:52:08,0,0,"<p>Here is the answer Judea Pearl <a href=""htt...",6965,None,...,None,None,2019-10-01 14:52:08,None,None,0,0,0,None,2019-10-01 14:52:08
4,419104,1,0,0,2019-07-25 04:01:36,2,38,<p>I am working with my resident survey data (...,249539,None,...,None,None,2019-07-25 04:48:35,Missing data imputation when all variables hav...,<missing-data><data-imputation>,1,0,0,None,None

In [ ]:
# Insert query to the queries table
store_query("Task 1", "Run the query to select 5 random row form the posts table", sql)

# Task 2: Create Single Table Queries

## Lifecycle Stage: Analyze
We can now start the analysis with our single-table queries.  First we need to create a new computed column to help with one of the queries.  The code below creates a column called LEN_BODY which is the length of the BODY text:

In [ ]:
%%sql
ALTER TABLE POSTS ADD COLUMN LEN_BODY INT

 * sqlite:///chatdata.db
Done.

[]

In [ ]:
%%sql
UPDATE POSTS SET LEN_BODY = LENGTH(BODY)

 * sqlite:///chatdata.db
42234 rows affected.

[]

### Single Table Queries
From the Template SQL Queries there are a series of queries requested. You are responsible for coding the result. Use the pattern above to accomplish the coding objective.  Copy and paste the question (column B Action) into a markdown cell and answer the query. Use the pattern that you have been using above.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter your code below.  Just keep on inserting cells as you need them.
    </font></div>

In [ ]:
# How many posts have 0 comments?
sql = """
    SELECT COUNT(CommentCount)
      FROM posts
      WHERE CommentCount == 0
    """
result = pd.read_sql(sql, con)
result

   COUNT(CommentCount)
0                21713

In [ ]:
## Insert query to the queries table
store_query("Task 2", "How many posts have 0 comments?", sql)

In [ ]:
# How many posts have 1 comments?
sql = """
    SELECT COUNT(CommentCount)
      FROM posts
      WHERE CommentCount == 1
    """
result = pd.read_sql(sql, con)
result

   COUNT(CommentCount)
0                 6460

In [ ]:
## Insert query to the queries table
store_query("Task 2", "How many posts have 1 comments?", sql)

In [ ]:
# How many posts have 2 comments or more?
sql = """
    SELECT COUNT(CommentCount)
      FROM posts
      WHERE CommentCount > 1
    """
result = pd.read_sql(sql, con)
result

   COUNT(CommentCount)
0                14061

In [ ]:
## Insert query to the queries table
store_query("Task 2", "How many posts have 2 comments or more?", sql)

In [ ]:
### The average CommentCount is 1.48. Checking number of comment from 1 to 3 make sense.
### However, it might be worth it to check out the outlier.
### E.g. the one with 66 comments and see what that is about
posts["CommentCount"].describe()

count    42234.000000
mean         1.482100
std          2.373247
min          0.000000
25%          0.000000
50%          0.000000
75%          2.000000
max         66.000000
Name: CommentCount, dtype: float64

In [ ]:
# Find the 5 posts with the highest viewcount
sql = """
    SELECT * FROM posts
      ORDER BY ViewCount DESC
      LIMIT 5
    """
result = pd.read_sql(sql, con)
result

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,LEN_BODY
0,388566,1,388582,0,2019-01-22 15:16:47,56,19542,"<ul>\n<li>Statement One (S1): ""One in 80 death...",228214,None,...,2019-01-22 21:40:39,2019-01-24 17:09:47,"Is it wrong to rephrase ""1 in 80 deaths is cau...",<interpretation><risk>,9,15,15,None,None,2270
1,394118,1,394128,0,2019-02-24 14:07:11,64,16317,<p>A human child at age 2 needs around 5 insta...,107213,None,...,2019-02-25 22:40:22,2019-03-03 17:37:05,Why do neural networks need so many training e...,<neural-networks><neuroscience>,12,24,38,None,None,512
2,431370,1,431397,0,2019-10-14 11:29:21,77,11723,<p>It seems very counter intuitive to many peo...,262594,None,...,2019-11-28 01:44:34,2019-11-28 01:44:34,Is there a name for the phenomenon of false po...,<probability><terminology><intuition>,8,9,18,None,None,811
3,398646,1,398653,0,2019-03-21 01:19:52,61,9850,<p>The title of the Comment in Nature <a href=...,163067,None,...,2019-03-22 22:14:04,2019-03-30 19:35:27,"What does ""Scientists rise up against statisti...",<statistical-significance><p-value><bias>,10,7,34,None,None,2148
4,434128,1,434579,0,2019-11-01 13:07:36,73,6718,<p>I am designing a one year program in data a...,14188,None,...,None,2019-11-26 00:59:15,Famous statistical wins and horror stories for...,<mathematical-statistics><data-visualization><...,13,7,70,None,2019-11-01 15:12:41,1172

In [ ]:
## Insert query to the queries table
store_query("Task 2", "Find the 5 posts with the highest viewcount", sql)

In [ ]:
# Find the top 5 posts with the highest scores
sql = """
    SELECT * FROM posts
      ORDER BY Score DESC
      LIMIT 5
    """
result = pd.read_sql(sql, con)
result

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,LEN_BODY
0,431397,2,0,431370,2019-10-14 14:29:36,101,0,<p>Yes there is. Generally it is termed <stron...,142976,None,...,None,2019-10-14 14:29:36,None,None,0,0,0,None,None,269
1,394128,2,0,394118,2019-02-24 15:44:44,100,0,<p>I caution against expecting strong resembla...,22311,None,...,2019-03-03 17:37:05,2019-03-03 17:37:05,None,None,0,15,0,None,None,5829
2,426878,2,0,426873,2019-09-11 23:23:31,93,0,<p><strong>tl;dr</strong> Even though this is ...,119015,None,...,2019-09-13 14:02:28,2019-09-13 14:02:28,None,None,0,6,0,None,None,4627
3,388578,2,0,388566,2019-01-22 15:48:47,80,0,"<p>To me ""1 in 80 deaths..."" is by far the cle...",227039,None,...,None,2019-01-22 15:48:47,None,None,0,11,0,None,None,572
4,431370,1,431397,0,2019-10-14 11:29:21,77,11723,<p>It seems very counter intuitive to many peo...,262594,None,...,2019-11-28 01:44:34,2019-11-28 01:44:34,Is there a name for the phenomenon of false po...,<probability><terminology><intuition>,8,9,18,None,None,811

In [ ]:
# Insert query to the queries table
store_query("Task 2", "Find the top 5 posts with the highest scores", sql)

In [ ]:
# What are the 5 most frequent scores on posts?
## Count all the groups of scores in the posts table, order them by the number of posts each group of score contains in descending order
## and limit them to top 5 groups.
### It was unclear what groupings were expected. E.g. group by a range of scores? or group by each answer?
### Scores below are group by value, i.e. post with score 4 group together.

sql = """
SELECT score, COUNT(Id) AS num FROM posts GROUP BY score ORDER BY num DESC LIMIT 5
"""

result = pd.read_sql(sql, con)
result

   Score    num
0      0  19888
1      1  11867
2      2   5094
3      3   2228
4      4   1059

In [ ]:
# Scores distribution
# Scores ranges from -11 to 101
posts["Score"].describe()

count    42234.000000
mean         1.135341
std          2.650514
min        -11.000000
25%          0.000000
50%          1.000000
75%          1.000000
max        101.000000
Name: Score, dtype: float64

In [ ]:
## There are 68 distinct score value
df = pd.DataFrame(posts['Score'].value_counts())
df.sort_index()

      Score
-11       1
-4        3
-3       22
-2       60
-1      369
...     ...
 77       1
 80       1
 93       1
 100      1
 101      1

[68 rows x 1 columns]

In [ ]:
# Insert query to the queries table
store_query("Task 2", "What are the 5 most frequent scores on posts?", sql)

In [ ]:
# How many posts have the keyword "data" in their tags?
## Notice that there are "<" in the tags column which you need to deal with by using like with %
sql = """
SELECT SUM((LENGTH(Tags)-LENGTH(REPLACE(Tags, "data", "")))/LENGTH("data")) FROM posts
"""

result = pd.read_sql(sql, con)
result

   SUM((LENGTH(Tags)-LENGTH(REPLACE(Tags, "data", "")))/LENGTH("data"))
0                                               2565

In [ ]:
## Insert query to the queries table
store_query("Task 2", "How many posts have the keyword 'data' in their tags?", sql)

In [ ]:
# What are the 5 most frequent commentcount for posts?
sql = """
SELECT CommentCount, COUNT(Id) AS num FROM Posts GROUP BY CommentCount ORDER BY num DESC LIMIT 5
"""

result = pd.read_sql(sql, con)
result

   CommentCount    num
0             0  21713
1             1   6460
2             2   4966
3             3   3063
4             4   2026

In [ ]:
## Insert query to the queries table
store_query("Task 2", "What are the 5 most frequent commentcount for posts?", sql)

In [ ]:
# How many posts have an accepted answer?
sql = """
SELECT COUNT(Id) FROM Posts WHERE AcceptedAnswerId <> 0
"""
result = pd.read_sql(sql, con)
result

   COUNT(Id)
0       5341

In [ ]:
## Insert query to the queries table
store_query("Task 2","How many posts have an accepted answer?", sql )

In [ ]:
# What is the average reputation of table users?
sql = """
    SELECT AVG(Reputation) FROM users
    """
result = pd.read_sql(sql, con)
result

   AVG(Reputation)
0       312.350912

In [ ]:
## Insert query to the queries table
store_query("Task 2", "What is the average reputation of table users?", sql)

In [ ]:
# What are the min reputation of users?
sql = """
    SELECT MIN(Reputation) FROM users
    """
result = pd.read_sql(sql, con)
result

   MIN(Reputation)
0                1

In [ ]:
## Insert query to the queries table
store_query("Task 2", "What are the min reputation of users?", sql )

In [ ]:
# What are the max reputation of users?
sql = """
    SELECT MAX(Reputation) FROM users
    """
result = pd.read_sql(sql, con)
result

   MAX(Reputation)
0           228662

In [ ]:
## Insert query to the queries table
store_query("Task 2", "What are the max reputation of users?", sql)

In [ ]:
# What is the length of the body of 5 most viewed posts?
sql = """
    SELECT ViewCount, LEN_BODY FROM posts ORDER BY ViewCount DESC LIMIT 5
    """
result = pd.read_sql(sql, con)
result

   ViewCount  LEN_BODY
0      19542      2270
1      16317       512
2      11723       811
3       9850      2148
4       6718      1172

In [ ]:
## Insert query to the queries table
store_query("Task 2", "What is the length of the body of 5 most viewed posts?", sql)

In [ ]:
# How many different locations are there in the users table?
sql ="""
SELECT COUNT(DISTINCT(Location)) FROM users
"""
result = pd.read_sql(sql, con)
result

   COUNT(DISTINCT(Location))
0                       1900

In [ ]:
## Insert query to the queries table
store_query("Task 2", "How many different locations are there in the users table?", sql)

In [ ]:
# What are the top 5 locations of users?
sql ="""
SELECT Location, COUNT(Id) AS num FROM users GROUP BY Location ORDER BY num DESC LIMIT 5
"""
result = pd.read_sql(sql, con)
result

        Location    num
0           None  13335
1        Germany    117
2          India    100
3  United States     69
4  Paris, France     66

In [ ]:
## Insert query to the queries table
store_query("Task 2", "What are the top 5 locations of users?", sql)

In [ ]:
# Location data quality check
## Data from location fields are inconistent. Responses are in county/city,
## even in full address and different languages.
%%sql SELECT location
FROM users
WHERE location glob '*[0-9]*'

 * sqlite:///chatdata.db
Done.

[('L_2',),
 ('1999法轮功，2018包子露宪',),
 ('District 9',),
 ('Greenwich, NJ 08323, United States',),
 ('4400 Fifth Avenue, Pittsburgh, PA, 15213',),
 ('Earth C-137',),
 ('x=0',),
 ('At location (3,4) in a spacious terrarium (somewhere in the Netherlands)',),
 ('2155 Sherwood Rd, San Marino, CA, USA',),
 ('ECE department, NIT Rourkela , National Institute of Technology, Sector 1, Rourkela, Odisha, India',),
 ('81',),
 ('0x08048000',),
 ('3 Macklin St, Pendle Hill NSW, Australia',),
 ('127.0.0.1',),
 ('Harrison, NJ 07029, USA',)]

In [ ]:
# Rank the days of the week from highest to lowest in terms of the volume of ViewCount as a percentage.

In [ ]:
# Create a new column week_day
%%sql
ALTER TABLE POSTS ADD COLUMN week_day INT

 * sqlite:///chatdata.db
Done.

[]

In [ ]:
%%sql
UPDATE POSTS SET week_day = CAST(strftime('%w', CreationDate) AS INTEGER)

 * sqlite:///chatdata.db
42234 rows affected.

[]

In [ ]:
sql = """
SELECT CASE week_day
          WHEN 0 THEN "Sunday"
          WHEN 1 THEN "Monday"
          WHEN 2 THEN "Tuesday"
          WHEN 3 THEN "Wednesday"
          WHEN 4 THEN "Thursday"
          WHEN 5 THEN "Friday"
          ELSE "Saturday"
      END AS week_day,

      100.0 * SUM(ViewCount) / (SELECT SUM(ViewCount) FROM posts) AS "percentage"

FROM posts
GROUP BY week_day
ORDER BY percentage DESC
"""
result = pd.read_sql(sql, con)
result

    week_day  percentage
0   Thursday   16.819476
1  Wednesday   16.768689
2    Tuesday   16.255034
3     Monday   15.806727
4     Friday   13.563061
5     Sunday   11.895609
6   Saturday    8.891404

In [ ]:
# Insert query to the queries table
store_query("Task 2", "Rank the days of the week from highest to lowest in terms of the volume of ViewCount as a percentage", sql )

In [ ]:
# Check result using pandas

sql = """
    SELECT week_day, SUM(ViewCount) FROM posts GROUP BY week_day
    """
ViewsByDay_df = pd.read_sql(sql, con)
Total_views = ViewsByDay_df['SUM(ViewCount)'].sum()
ViewsByDay_df["Percentage"] = ViewsByDay_df['SUM(ViewCount)']/Total_views * 100.0
ViewsByDay_df.sort_values(by=["Percentage"], ascending = False)

   week_day  SUM(ViewCount)  Percentage
4         4          331507   16.819476
3         3          330506   16.768689
2         2          320382   16.255034
1         1          311546   15.806727
5         5          267324   13.563061
0         0          234459   11.895609
6         6          175247    8.891404

# Task 3: Cross Table Queries

## Lifecycle Stage: Analyze
Let's continue the analysis with our multi-table queries.

### Cross Table Queries (Inner Join)

From the Template SQL Queries there are a series of queries requested. You are responsible for coding the result. Use the pattern above to accomplish the coding objective.  Copy and paste the question (column B Action) into a markdown cell and answer the query. Use the pattern that you have been using above.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter your code below.  Just keep on inserting cells as you need them.
    </font></div>

In [ ]:
# How many posts have been created by a user that has a filled out the "AboutMe" section?
%%sql
SELECT COUNT(posts.Id)
  FROM posts JOIN users on (posts.OwnerUserId = users.Id)
  WHERE users.AboutMe IS NOT NULL

 * sqlite:///chatdata.db
Done.

[(17189,)]

In [ ]:
# Insert query to the queries table
store_query("Task 3", "How many posts have been created by a user that has a filled out the 'AboutMe' section?", sql )

In [ ]:
# Number of users with about "AboutMe"
%%sql
SELECT COUNT(DISTINCT users.Id)
FROM users
  WHERE users.AboutMe IS NOT NULL

 * sqlite:///chatdata.db
Done.

[(4021,)]

In [ ]:
# Considering only the users with an "AboutMe," how many posts are there per user?
sql = """
SELECT CAST(COUNT(posts.Id) AS FLOAT) / (SELECT COUNT(DISTINCT users.Id) FROM users WHERE users.AboutMe IS NOT NULL)
  FROM posts JOIN users on (posts.OwnerUserId = users.Id)
  WHERE users.AboutMe IS NOT NULL
"""

result = pd.read_sql(sql, con)
result

   CAST(COUNT(posts.Id) AS FLOAT) / (SELECT COUNT(DISTINCT users.Id) FROM users WHERE users.AboutMe IS NOT NULL)
0                                           4.274807

In [ ]:
# Insert query to the queries table
store_query("Task 3", "Considering only the users with an 'AboutMe,' how many posts are there per user?", sql )

In [ ]:
# "Not taking into account the commentcount field in the table posts, what are the Top 10 posts in terms of number of comments?
sql = """
SELECT Comments.PostId, COUNT(Comments.Id), Posts.Body
FROM comments JOIN posts on (comments.postId = posts.Id)
GROUP BY Comments.PostId ORDER BY COUNT (Comments.Id) DESC
LIMIT 10
"""

result = pd.read_sql(sql, con)
result

,PostId,COUNT(Comments.Id),Body
0,386853,66,<p>Are the 148 regions together spanning the e...
1,386556,34,<p><strong>Background</strong></p>\n\n<p>As an...
2,418910,31,<p>Let's start with the regular Monty Hall pro...
3,395232,31,<p>Why we don't choose other distributions?—we...
4,402987,27,<p>I am looking for some comprehensive instruc...
5,386075,26,<p>I have questions inspired from the Amazon r...
6,394118,24,<p>A human child at age 2 needs around 5 insta...
7,402950,23,<p>I'd like to use a fixed-effect <strong>Pois...
8,398828,23,<p><strong><em>tl;dr</em>-</strong> It's fund...
9,396111,22,"<p>I am rather new to the TSNE method, and am ..."

In [ ]:
# Insert query to the queries table
store_query("Task 3", "Not taking into account the commentcount field in the table posts, what are the Top 10 posts in terms of number of comments?", sql)

In [ ]:
# "What are the Top 10 posts which have the highest cummulative (post score + comment score) score?
sql = """
SELECT SUM(posts.score + comments.score) AS "cummulative score (post score + comment score)", comments.PostId, Posts.Body
FROM comments JOIN posts on (comments.postId = posts.Id)
GROUP BY comments.PostId ORDER BY SUM(posts.score + comments.score) DESC
LIMIT 10
"""

result = pd.read_sql(sql, con)
result

,cummulative score (post score + comment score),PostId,Body
0,1778,394118,<p>A human child at age 2 needs around 5 insta...
1,1569,394128,<p>I caution against expecting strong resembla...
2,1094,418910,<p>Let's start with the regular Monty Hall pro...
3,1021,398653,"<p>The first three points, as far as I can tel..."
4,941,388578,"<p>To me ""1 in 80 deaths..."" is by far the cle..."
5,885,388566,"<ul>\n<li>Statement One (S1): ""One in 80 death..."
6,808,396818,<p>That definition is a somewhat awkward way t...
7,621,418814,<p>To add a visual explanation to this: let's ...
8,570,394258,<p>One major aspect that I don't see in curren...
9,566,394439,"<p>This <a href=""https://www.reuters.com/artic..."

In [ ]:
# Insert query to the queries table
store_query("Task 3", "What are the Top 10 posts which have the highest cummulative (post score + comment score) score?", sql)

In [ ]:
# Who are the top 10 users who comment the most?
sql = """
SELECT users.Id, users.Reputation, COUNT(comments.UserId) AS "Number of comments posted"
FROM users JOIN comments on (users.Id = comments.UserId)
GROUP BY users.Id ORDER BY COUNT(comments.UserId) DESC
LIMIT 10
"""

result = pd.read_sql(sql, con)
result

       Id  Reputation  Number of comments posted
0     919      223056                       3301
1     805      228662                       1153
2  143489        2890                       1024
3   11887       39200                        805
4   85665       17391                        691
5  164061       13485                        540
6   22047       41385                        536
7  158565        6482                        504
8    7962        8030                        492
9   35989       71548                        470

In [ ]:
# Insert query to the queries table
store_query("Task 3", "Who are the top 10 users who comment the most?", sql)

In [ ]:
# Who are the top 10 users who post the most?
sql = """
SELECT users.Id, users.DisplayName, users.AccountId, COUNT(posts.Id) AS "Number of posts"
FROM posts JOIN users on (posts.OwnerUserId = users.Id)
GROUP BY posts.OwnerUserId ORDER BY COUNT(posts.Id) DESC
LIMIT 10
"""

result = pd.read_sql(sql, con)
result

       Id                    DisplayName  AccountId  Number of posts
0  204068                          gunes    3387323              637
1   85665                        BruceET    5902228              545
2  173082               Reinstate Monica   11521300              435
3   11887             kjetil b halvorsen     215207              435
4     686  Peter Flom - Reinstate Monica      80800              386
5    1352  S. Kolassa - Reinstate Monica     204092              285
6    3382                      IrishStat     509726              274
7    7224                          Xi'an     844516              233
8   35989                            Tim    2242720              230
9     805       Glen_b -Reinstate Monica     131001              230

In [ ]:
# Insert query to the queries table
store_query("Task 3", "Who are the top 10 users who post the most?", sql)

### Stretch Task: Cross Table Queries by Left Join
** Stretch task using left join. Found orphan comments without original posts. Queries in this section are not store in the queries table.

From the Template SQL Queries there are a series of queries requested. You are responsible for coding the result. Use the pattern above to accomplish the coding objective.  Copy and paste the question (column B Action) into a markdown cell and answer the query. Use the pattern that you have been using above.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Enter your code below.  Just keep on inserting cells as you need them.
    </font></div>

In [ ]:
# How many posts have been created by a user that has a filled out the "AboutMe" section?
%%sql
SELECT COUNT(posts.Id)
  FROM posts LEFT JOIN users on (posts.OwnerUserId = users.Id)
  WHERE users.AboutMe IS NOT NULL

 * sqlite:///chatdata.db
Done.

[(17189,)]

In [ ]:
# Number of users with about "AboutMe"
%%sql
SELECT COUNT(DISTINCT users.Id)
FROM users
  WHERE users.AboutMe IS NOT NULL

 * sqlite:///chatdata.db
Done.

[(4021,)]

In [ ]:
# Considering only the users with an "AboutMe," how many posts are there per user?
sql = """
SELECT CAST(COUNT(posts.Id) AS FLOAT) / (SELECT COUNT(DISTINCT users.Id) FROM users WHERE users.AboutMe IS NOT NULL)
  FROM posts LEFT JOIN users on (posts.OwnerUserId = users.Id)
  WHERE users.AboutMe IS NOT NULL
"""

result = pd.read_sql(sql, con)

In [ ]:
# "Not taking into account the commentcount field in the table posts, what are the Top 10 posts in terms of number of comments?
sql = """
SELECT Comments.PostId, COUNT(Comments.Id), Posts.Body
FROM comments LEFT JOIN posts on (comments.postId = posts.Id)
GROUP BY Comments.PostId ORDER BY COUNT (Comments.Id) DESC
LIMIT 10
"""

result = pd.read_sql(sql, con)
result

,PostId,COUNT(Comments.Id),Body
0,386853,66,<p>Are the 148 regions together spanning the e...
1,384936,42,None
2,386556,34,<p><strong>Background</strong></p>\n\n<p>As an...
3,418910,31,<p>Let's start with the regular Monty Hall pro...
4,395232,31,<p>Why we don't choose other distributions?—we...
5,402987,27,<p>I am looking for some comprehensive instruc...
6,386075,26,<p>I have questions inspired from the Amazon r...
7,394118,24,<p>A human child at age 2 needs around 5 insta...
8,335381,24,None
9,402950,23,<p>I'd like to use a fixed-effect <strong>Pois...

In [ ]:
# Checking post with null Posts.Body. Post does not exist in posts table? Orphan comments?
posts[posts["Id"]==335381]

Empty DataFrame
Columns: [Id, PostTypeId, AcceptedAnswerId, ParentId, CreationDate, Score, ViewCount, Body, OwnerUserId, OwnerDisplayName, LastEditorUserId, LastEditorDisplayName, LastEditDate, LastActivityDate, Title, Tags, AnswerCount, CommentCount, FavoriteCount, ClosedDate, CommunityOwnedDate]
Index: []

[0 rows x 21 columns]

In [ ]:
# Are these orphan comments?
comments[comments["PostId"]==335381]

,Id,PostId,Score,Text,CreationDate,UserId
7141,733264,335381,0,@PeterWestfall I agree that Moors' interpretat...,2019-02-02 23:20:00,99274
7206,733354,335381,0,"""Leverage"" refers to the first moment of the v...",2019-02-03 13:40:59,102879
7302,733501,335381,0,"@PeterWestfall Not to be too punny, but you ar...",2019-02-04 04:27:10,99274
7303,733502,335381,0,@PeterWestfall In the context of circular moti...,2019-02-04 04:31:19,99274
7432,733930,335381,0,"@PeterWestfall Mean, fulcrum, axis of rotation...",2019-02-05 14:07:32,99274
7586,733218,335381,0,Skewness is the balance point of the pdf of $Z...,2019-02-02 17:47:29,102879
7717,734450,335381,0,"Ok, so maybe kurtosis is better called ""tail f...",2019-02-06 19:14:22,102879
7728,734265,335381,0,Why? I thought that if a fulcrum is placed on ...,2019-02-06 13:14:08,102879
7741,734461,335381,0,@PeterWestfall I think kurtosis for time as th...,2019-02-06 20:09:34,99274
7828,734509,335381,0,"Hmmm, that's not particularly helpful. Kurtosi...",2019-02-06 22:28:34,102879
7852,734354,335381,0,"Keeping this simple, one does not generally ex...",2019-02-06 15:30:44,99274
7881,734554,335381,0,@PeterWestfall Is an axis of rotation a balanc...,2019-02-07 03:20:40,99274
8023,733783,335381,0,Please reread my comment above. The leverage c...,2019-02-04 22:34:15,102879
8035,733797,335381,0,"Also, the physical understanding of variance a...",2019-02-04 23:49:49,102879
8664,735007,335381,0,"Can you say ""red herring""? Obviously we are r...",2019-02-08 13:08:16,102879
8670,735021,335381,0,@PeterWestfall I am not refuting your internal...,2019-02-08 13:41:16,99274
8671,735025,335381,0,"@PeterWestfall con't ..."" Notice that the para...",2019-02-08 13:49:26,99274
13063,741589,335381,0,Let $v = z^4$. The $v$ is in 1 dimension; no m...,2019-03-03 16:51:36,102879
13095,741615,335381,0,"@PeterWestfall Alternatively, note that the fo...",2019-03-03 19:04:30,99274
13121,741635,335381,0,@PeterWestfall This discussion is concerning s...,2019-03-03 20:29:28,99274
13315,741873,335381,0,"The term ""not falsifiable"" connotes triviality...",2019-03-04 17:00:27,102879
13423,742023,335381,0,@PeterWestfall I am not trivializing what you ...,2019-03-05 01:29:22,99274
13425,742026,335381,0,@PeterWestfall ....to calculate kurtosis. I av...,2019-03-05 01:39:27,99274
13443,742049,335381,0,"@PeterWestfall Despite the language problems, ...",2019-03-05 04:44:56,99274

In [ ]:
# "What are the Top 10 posts which have the highest cummulative (post score + comment score) score?
sql = """
SELECT SUM(posts.score + comments.score) AS "cummulative score (post score + comment score)", comments.PostId, Posts.Body
FROM comments LEFT JOIN posts on (comments.postId = posts.Id)
GROUP BY comments.PostId ORDER BY SUM(posts.score + comments.score) DESC
LIMIT 10
"""

result = pd.read_sql(sql, con)
result

,cummulative score (post score + comment score),PostId,Body
0,1778,394118,<p>A human child at age 2 needs around 5 insta...
1,1569,394128,<p>I caution against expecting strong resembla...
2,1094,418910,<p>Let's start with the regular Monty Hall pro...
3,1021,398653,"<p>The first three points, as far as I can tel..."
4,941,388578,"<p>To me ""1 in 80 deaths..."" is by far the cle..."
5,885,388566,"<ul>\n<li>Statement One (S1): ""One in 80 death..."
6,808,396818,<p>That definition is a somewhat awkward way t...
7,621,418814,<p>To add a visual explanation to this: let's ...
8,570,394258,<p>One major aspect that I don't see in curren...
9,566,394439,"<p>This <a href=""https://www.reuters.com/artic..."

In [ ]:
# Who are the top 10 users who comment the most?
sql = """
SELECT users.Id, users.Reputation, COUNT(comments.UserId) AS "Number of comments posted"
FROM users LEFT JOIN comments on (users.Id = comments.UserId)
GROUP BY users.Id ORDER BY COUNT(comments.UserId) DESC
LIMIT 10
"""

result = pd.read_sql(sql, con)
result

       Id  Reputation  Number of comments posted
0     919      223056                       3301
1     805      228662                       1153
2  143489        2890                       1024
3   11887       39200                        805
4   85665       17391                        691
5  164061       13485                        540
6   22047       41385                        536
7  158565        6482                        504
8    7962        8030                        492
9   35989       71548                        470

In [ ]:
# Who are the top 10 users who post the most?
sql = """
SELECT users.Id, users.DisplayName, users.AccountId, COUNT(posts.Id) AS "Number of posts"
FROM posts left join users on (posts.OwnerUserId = users.Id)
GROUP BY posts.OwnerUserId ORDER BY COUNT(posts.Id) DESC
LIMIT 10
"""

result = pd.read_sql(sql, con)
result

         Id                    DisplayName   AccountId  Number of posts
0  204068.0                          gunes   3387323.0              637
1   85665.0                        BruceET   5902228.0              545
2  173082.0               Reinstate Monica  11521300.0              435
3   11887.0             kjetil b halvorsen    215207.0              435
4     686.0  Peter Flom - Reinstate Monica     80800.0              386
5    1352.0  S. Kolassa - Reinstate Monica    204092.0              285
6    3382.0                      IrishStat    509726.0              274
7       NaN                           None         NaN              247
8    7224.0                          Xi'an    844516.0              233
9   35989.0                            Tim   2242720.0              230

# Task 4: Check the Queries Table

Now let's tidy up and check the queries table.

First let's check it's contents:

In [ ]:
%sql SELECT * FROM queries

 * sqlite:///chatdata.db
Done.

[('Single Table Queries', 'Which 5 users have viewed the most times and what is the sum of those views per user?', '\nSELECT Id, SUM(Views) AS TotalViews\n    FROM Users\n        GROUP BY Id\n            ORDER BY TotalViews DESC\n                LIMIT 5\n                '),
 ('Task 1', 'Create table comments', '\n    CREATE TABLE "comments" (\n    "Id" INTEGER,\n    "PostId" INTEGER,\n    "Score" INTEGER,\n    "Text" TEXT,\n    "CreationDate" TEXT,\n    "UserId" INTEGER\n    )\n    '),
 ('Task 1', 'Create table posts', '\n    CREATE TABLE "posts" (\n    "Id" INTEGER NOT NULL PRIMARY KEY,\n    "PostTypeId" INTEGER,\n    "AcceptedAnswerId" INTEGER,\n    "ParentId" INTE ... (321 characters truncated) ... "AnswerCount" INTEGER,\n    "CommentCount" INTEGER,\n    "FavoriteCount" INTEGER,\n    "ClosedDate" TEXT,\n    "CommunityOwnedDate" TEXT\n    )\n    '),
 ('Task 1', 'Create table users', '\n  CREATE TABLE "comments" (\n  "Id" INTEGER NOT NULL PRIMARY KEY,\n  "PostId" INTEGER,\n  "Score" INTEGER,\n  "Text" TEXT,\n  "CreationDate" TEXT,\n  "UserId" INTEGER,\n  FOREIGN KEY (PostId)\n    REFERENCES posts (Id),\n  FOREIGN KEY (UserId)\n    REFERENCES users (Id)\n  )\n  '),
 ('Task 1', 'Count the number of rows in the comments table', '\n    SELECT COUNT(*) FROM comments\n    '),
 ('Task 1', 'Count the number of rows in the users table', '\n    SELECT COUNT(*) FROM users\n    '),
 ('Task 1', 'Count the number of rows in the posts table', '\n    SELECT COUNT(*) FROM posts\n    '),
 ('Task 1', 'Run the query to select 5 random rows from the comments table', '\n    SELECT * FROM comments order by random() limit 5\n    '),
 ('Task 1', 'Run the query to select 5 random rows from the users table', '\n    SELECT * FROM users order by random() limit 5\n    '),
 ('Task 1', 'Run the query to select 5 random row form the posts table', '\n    SELECT * FROM posts order by random() limit 5\n    '),
 ('Task 2', 'How many posts have 0 comments?', '\n    SELECT COUNT(CommentCount)\n      FROM posts\n      WHERE CommentCount == 0\n    '),
 ('Task 2', 'How many posts have 1 comments?', '\n    SELECT COUNT(CommentCount)\n      FROM posts\n      WHERE CommentCount == 1\n    '),
 ('Task 2', 'How many posts have 2 comments or more?', '\n    SELECT COUNT(CommentCount)\n      FROM posts\n      WHERE CommentCount > 1\n    '),
 ('Task 2', 'Find the 5 posts with the highest viewcount', '\n    SELECT * FROM posts\n      ORDER BY ViewCount DESC\n      LIMIT 5\n    '),
 ('Task 2', 'Find the top 5 posts with the highest scores', '\n    SELECT * FROM posts\n      ORDER BY Score DESC\n      LIMIT 5\n    '),
 ('Task 2', 'What are the 5 most frequent scores on posts?', '\nSELECT score, COUNT(Id) AS num FROM posts GROUP BY score ORDER BY num DESC LIMIT 5\n'),
 ('Task 2', "How many posts have the keyword 'data' in their tags?", '\nSELECT SUM((LENGTH(Tags)-LENGTH(REPLACE(Tags, "data", "")))/LENGTH("data")) FROM posts\n'),
 ('Task 2', 'What are the 5 most frequent commentcount for posts?', '\nSELECT CommentCount, COUNT(Id) AS num FROM Posts GROUP BY CommentCount ORDER BY num DESC LIMIT 5\n'),
 ('Task 2', 'How many posts have an accepted answer?', '\nSELECT COUNT(Id) FROM Posts WHERE AcceptedAnswerId <> 0\n'),
 ('Task 2', 'What is the average reputation of table users?', '\n    SELECT AVG(Reputation) FROM users\n    '),
 ('Task 2', 'What are the min reputation of users?', '\n    SELECT MIN(Reputation) FROM users\n    '),
 ('Task 2', 'What are the max reputation of users?', '\n    SELECT MAX(Reputation) FROM users\n    '),
 ('Task 2', 'What is the length of the body of 5 most viewed posts?', '\n    SELECT ViewCount, LEN_BODY FROM posts ORDER BY ViewCount DESC LIMIT 5\n    '),
 ('Task 2', 'How many different locations are there in the users table?', '\nSELECT COUNT(DISTINCT(Location)) FROM users\n'),
 ('Task 2', 'What are the top 5 locations of users?', '\nSELECT Location, COUNT(Id) AS num FROM users GROUP BY Location ORDER BY num DESC LIMIT 5\n'),
 ('Task 2', 'Rank the days of the week from highest to lowest in terms of the volume of ViewCount as a percentage', '\nSELECT CASE week_day\n          WHEN 0 THEN "Sunday"\n          WHEN 1 THEN "Monday"\n          WHEN 2 THEN "Tuesday"\n          WHEN 3 THEN "Wedne ... (119 characters truncated) ... ay,\n\n      100.0 * SUM(ViewCount) / (SELECT SUM(ViewCount) FROM posts) AS "percentage"\n\nFROM posts\nGROUP BY week_day\nORDER BY percentage DESC\n'),
 ('Task 3', "How many posts have been created by a user that has a filled out the 'AboutMe' section?", '\n    SELECT week_day, SUM(ViewCount) FROM posts GROUP BY week_day\n    '),
 ('Task 3', "Considering only the users with an 'AboutMe,' how many posts are there per user?", '\nSELECT CAST(COUNT(posts.Id) AS FLOAT) / (SELECT COUNT(DISTINCT users.Id) FROM users WHERE users.AboutMe IS NOT NULL)\n  FROM posts JOIN users on (posts.OwnerUserId = users.Id)\n  WHERE users.AboutMe IS NOT NULL\n'),
 ('Task 3', 'Not taking into account the commentcount field in the table posts, what are the Top 10 posts in terms of number of comments?', '\nSELECT Comments.PostId, COUNT(Comments.Id), Posts.Body\nFROM comments JOIN posts on (comments.postId = posts.Id)\nGROUP BY Comments.PostId ORDER BY COUNT (Comments.Id) DESC\nLIMIT 10\n'),
 ('Task 3', 'What are the Top 10 posts which have the highest cummulative (post score + comment score) score?', '\nSELECT SUM(posts.score + comments.score) AS "cummulative score (post score + comment score)", comments.PostId, Posts.Body\nFROM comments JOIN posts on (comments.postId = posts.Id)\nGROUP BY comments.PostId ORDER BY SUM(posts.score + comments.score) DESC\nLIMIT 10\n'),
 ('Task 3', 'Who are the top 10 users who comment the most?', '\nSELECT users.Id, users.Reputation, COUNT(comments.UserId) AS "Number of comments posted"\nFROM users JOIN comments on (users.Id = comments.UserId)\nGROUP BY users.Id ORDER BY COUNT(comments.UserId) DESC\nLIMIT 10\n'),
 ('Task 3', 'Who are the top 10 users who post the most?', '\nSELECT users.Id, users.DisplayName, users.AccountId, COUNT(posts.Id) AS "Number of posts"\nFROM posts JOIN users on (posts.OwnerUserId = users.Id)\nGROUP BY posts.OwnerUserId ORDER BY COUNT(posts.Id) DESC\nLIMIT 10\n')]

## Drop Duplicates

You likely have some duplicates. Lets drop them.

In [ ]:
# Read the queries table into pandas
sql = 'SELECT * FROM queries'
queries = pd.read_sql(sql, con)

# Drop duplicates
queries.drop_duplicates(inplace = True) # drop duplicates

## Case Issues

Remember, SQL is case insensitive. Pandas IS case sensitive. Lets deal with this now by making all of the text uppercase.

In [ ]:
for col in queries.columns:
    queries[col] = queries[col].str.upper()

queries

,task,action,query
0,SINGLE TABLE QUERIES,WHICH 5 USERS HAVE VIEWED THE MOST TIMES AND W...,"\nSELECT ID, SUM(VIEWS) AS TOTALVIEWS\n FRO..."
1,TASK 1,CREATE TABLE COMMENTS,"\n CREATE TABLE ""COMMENTS"" (\n ""ID"" INTE..."
2,TASK 1,CREATE TABLE POSTS,"\n CREATE TABLE ""POSTS"" (\n ""ID"" INTEGER..."
3,TASK 1,CREATE TABLE USERS,"\n CREATE TABLE ""COMMENTS"" (\n ""ID"" INTEGER ..."
4,TASK 1,COUNT THE NUMBER OF ROWS IN THE COMMENTS TABLE,\n SELECT COUNT(*) FROM COMMENTS\n
5,TASK 1,COUNT THE NUMBER OF ROWS IN THE USERS TABLE,\n SELECT COUNT(*) FROM USERS\n
6,TASK 1,COUNT THE NUMBER OF ROWS IN THE POSTS TABLE,\n SELECT COUNT(*) FROM POSTS\n
7,TASK 1,RUN THE QUERY TO SELECT 5 RANDOM ROWS FROM THE...,\n SELECT * FROM COMMENTS ORDER BY RANDOM()...
8,TASK 1,RUN THE QUERY TO SELECT 5 RANDOM ROWS FROM THE...,\n SELECT * FROM USERS ORDER BY RANDOM() LI...
9,TASK 1,RUN THE QUERY TO SELECT 5 RANDOM ROW FORM THE ...,\n SELECT * FROM POSTS ORDER BY RANDOM() LI...
10,TASK 2,HOW MANY POSTS HAVE 0 COMMENTS?,\n SELECT COUNT(COMMENTCOUNT)\n FROM P...
11,TASK 2,HOW MANY POSTS HAVE 1 COMMENTS?,\n SELECT COUNT(COMMENTCOUNT)\n FROM P...
12,TASK 2,HOW MANY POSTS HAVE 2 COMMENTS OR MORE?,\n SELECT COUNT(COMMENTCOUNT)\n FROM P...
13,TASK 2,FIND THE 5 POSTS WITH THE HIGHEST VIEWCOUNT,\n SELECT * FROM POSTS\n ORDER BY VIEW...
14,TASK 2,FIND THE TOP 5 POSTS WITH THE HIGHEST SCORES,\n SELECT * FROM POSTS\n ORDER BY SCOR...
15,TASK 2,WHAT ARE THE 5 MOST FREQUENT SCORES ON POSTS?,"\nSELECT SCORE, COUNT(ID) AS NUM FROM POSTS GR..."
16,TASK 2,HOW MANY POSTS HAVE THE KEYWORD 'DATA' IN THEI...,\nSELECT SUM((LENGTH(TAGS)-LENGTH(REPLACE(TAGS...
17,TASK 2,WHAT ARE THE 5 MOST FREQUENT COMMENTCOUNT FOR ...,"\nSELECT COMMENTCOUNT, COUNT(ID) AS NUM FROM P..."
18,TASK 2,HOW MANY POSTS HAVE AN ACCEPTED ANSWER?,\nSELECT COUNT(ID) FROM POSTS WHERE ACCEPTEDAN...
19,TASK 2,WHAT IS THE AVERAGE REPUTATION OF TABLE USERS?,\n SELECT AVG(REPUTATION) FROM USERS\n
20,TASK 2,WHAT ARE THE MIN REPUTATION OF USERS?,\n SELECT MIN(REPUTATION) FROM USERS\n
21,TASK 2,WHAT ARE THE MAX REPUTATION OF USERS?,\n SELECT MAX(REPUTATION) FROM USERS\n
22,TASK 2,WHAT IS THE LENGTH OF THE BODY OF 5 MOST VIEWE...,"\n SELECT VIEWCOUNT, LEN_BODY FROM POSTS OR..."
23,TASK 2,HOW MANY DIFFERENT LOCATIONS ARE THERE IN THE ...,\nSELECT COUNT(DISTINCT(LOCATION)) FROM USERS\n
24,TASK 2,WHAT ARE THE TOP 5 LOCATIONS OF USERS?,"\nSELECT LOCATION, COUNT(ID) AS NUM FROM USERS..."
25,TASK 2,RANK THE DAYS OF THE WEEK FROM HIGHEST TO LOWE...,\nSELECT CASE WEEK_DAY\n WHEN 0 THEN ...
26,TASK 3,HOW MANY POSTS HAVE BEEN CREATED BY A USER THA...,"\n SELECT WEEK_DAY, SUM(VIEWCOUNT) FROM POS..."
27,TASK 3,"CONSIDERING ONLY THE USERS WITH AN 'ABOUTME,' ...",\nSELECT CAST(COUNT(POSTS.ID) AS FLOAT) / (SEL...
28,TASK 3,NOT TAKING INTO ACCOUNT THE COMMENTCOUNT FIELD...,"\nSELECT COMMENTS.POSTID, COUNT(COMMENTS.ID), ..."
29,TASK 3,WHAT ARE THE TOP 10 POSTS WHICH HAVE THE HIGHE...,\nSELECT SUM(POSTS.SCORE + COMMENTS.SCORE) AS ...
30,TASK 3,WHO ARE THE TOP 10 USERS WHO COMMENT THE MOST?,"\nSELECT USERS.ID, USERS.REPUTATION, COUNT(COM..."
31,TASK 3,WHO ARE THE TOP 10 USERS WHO POST THE MOST?,"\nSELECT USERS.ID, USERS.DISPLAYNAME, USERS.AC..."

In [ ]:
# Write the now deduped uppercase dataframe back to sqlite and replace the table
queries.to_sql('queries', con, if_exists='replace', index=False)

32

## Use Case

Now that we have this queries table, lets give you some ideas about how you would use it.

Suppose you wanted to find all of the queries where you did a GROUP BY:

In [ ]:
%%sql
SELECT query
    FROM queries
        WHERE query LIKE '%GROUP BY%'

 * sqlite:///chatdata.db
Done.

[('\nSELECT ID, SUM(VIEWS) AS TOTALVIEWS\n    FROM USERS\n        GROUP BY ID\n            ORDER BY TOTALVIEWS DESC\n                LIMIT 5\n                ',),
 ('\nSELECT SCORE, COUNT(ID) AS NUM FROM POSTS GROUP BY SCORE ORDER BY NUM DESC LIMIT 5\n',),
 ('\nSELECT COMMENTCOUNT, COUNT(ID) AS NUM FROM POSTS GROUP BY COMMENTCOUNT ORDER BY NUM DESC LIMIT 5\n',),
 ('\nSELECT LOCATION, COUNT(ID) AS NUM FROM USERS GROUP BY LOCATION ORDER BY NUM DESC LIMIT 5\n',),
 ('\nSELECT CASE WEEK_DAY\n          WHEN 0 THEN "SUNDAY"\n          WHEN 1 THEN "MONDAY"\n          WHEN 2 THEN "TUESDAY"\n          WHEN 3 THEN "WEDNE ... (119 characters truncated) ... AY,\n\n      100.0 * SUM(VIEWCOUNT) / (SELECT SUM(VIEWCOUNT) FROM POSTS) AS "PERCENTAGE"\n\nFROM POSTS\nGROUP BY WEEK_DAY\nORDER BY PERCENTAGE DESC\n',),
 ('\n    SELECT WEEK_DAY, SUM(VIEWCOUNT) FROM POSTS GROUP BY WEEK_DAY\n    ',),
 ('\nSELECT COMMENTS.POSTID, COUNT(COMMENTS.ID), POSTS.BODY\nFROM COMMENTS JOIN POSTS ON (COMMENTS.POSTID = POSTS.ID)\nGROUP BY COMMENTS.POSTID ORDER BY COUNT (COMMENTS.ID) DESC\nLIMIT 10\n',),
 ('\nSELECT SUM(POSTS.SCORE + COMMENTS.SCORE) AS "CUMMULATIVE SCORE (POST SCORE + COMMENT SCORE)", COMMENTS.POSTID, POSTS.BODY\nFROM COMMENTS JOIN POSTS ON (COMMENTS.POSTID = POSTS.ID)\nGROUP BY COMMENTS.POSTID ORDER BY SUM(POSTS.SCORE + COMMENTS.SCORE) DESC\nLIMIT 10\n',),
 ('\nSELECT USERS.ID, USERS.REPUTATION, COUNT(COMMENTS.USERID) AS "NUMBER OF COMMENTS POSTED"\nFROM USERS JOIN COMMENTS ON (USERS.ID = COMMENTS.USERID)\nGROUP BY USERS.ID ORDER BY COUNT(COMMENTS.USERID) DESC\nLIMIT 10\n',),
 ('\nSELECT USERS.ID, USERS.DISPLAYNAME, USERS.ACCOUNTID, COUNT(POSTS.ID) AS "NUMBER OF POSTS"\nFROM POSTS JOIN USERS ON (POSTS.OWNERUSERID = USERS.ID)\nGROUP BY POSTS.OWNERUSERID ORDER BY COUNT(POSTS.ID) DESC\nLIMIT 10\n',)]

## Now Your Turn
Find the queries that have 'DISTINCT' in them. You can do it with the %sql command or with Pandas and sql.

<div style="background-color:lemonchiffon; border:1px solid; padding:5px; margin:5px; font-weight:bold"><font color="crimson">
TODO: Complete the following code cell
    </font></div>

In [ ]:
# TODO
%%sql
SELECT query
    FROM queries
        WHERE query LIKE '%DISTINCT%'

 * sqlite:///chatdata.db
Done.

[('\nSELECT COUNT(DISTINCT(LOCATION)) FROM USERS\n',),
 ('\nSELECT CAST(COUNT(POSTS.ID) AS FLOAT) / (SELECT COUNT(DISTINCT USERS.ID) FROM USERS WHERE USERS.ABOUTME IS NOT NULL)\n  FROM POSTS JOIN USERS ON (POSTS.OWNERUSERID = USERS.ID)\n  WHERE USERS.ABOUTME IS NOT NULL\n',)]

# Close SQLite

It is good practise to close all relational databases as soon as you are finished updating them.

In [ ]:
#con.close()

# All Done!

Great job. You now have a good idea for how to use sql and pandas with sql. You can create your own databases from csv files and you can do extensive querying using sql. These are valuable skills that will take you a long ways in todays technological world.